### ISSUE TITLE
refactor: remove global variables

### ISSUE THREAD

**Issue by manticode** [manticode/autodrop#22]
Global vars are being set... refactor so there are no global vars.

**Comment by GregoryNavasarkian** [comment]
@manticode I added PR #23 just as an idea. 
Not sure that is what you were going for...

**Comment by manticode** [comment]
@GregoryNavasarkian thanks for commenting and your suggestion. That's very close to what I had in mind to be honest!

My thoughts were to set default config values to the ConfigParser object directly.

For example:
```
config_vars = config['autodrop']
config_vars.setdefault('rsync_path', '/usr/bin/rsync')
```

This will help avoid duplication.
